### ISSUE TITLE
error in suds-jurko setup command: use_2to3 is invalid.

### ISSUE THREAD

**Issue by smallfish01** [Affirm/suds-jurko#5]
Hello,

When I install suds-jurko in my Centos server, I got the follow error:
error in suds-jurko setup command: use_2to3 is invalid.

My OS version is: Centos 7.9
Python version is: 3.9.7

# python --version
Python 3.9.7

# pip list
Package            Version
------------------ ---------
certifi            2021.5.30
charset-normalizer 2.0.4
idna               3.2
lxml               4.6.3
pip                21.2.4
pyvmomi            7.0.2
requests           2.26.0
setuptools         58.0.4
six                1.16.0
urllib3            1.26.6

If I running pip instlal suds-jurko also got error:

# pip install suds-jurko
Collecting suds-jurko
  Using cached suds-jurko-0.6.zip (255 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/venv/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-06sba9tu/suds-jurko_1ae1d95cd1104cee91119ee45df0c3d1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-06sba9tu/suds-jurko_1ae1d95cd1104cee91119ee45df0c3d1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-8bmasmyw
         cwd: /tmp/pip-install-06sba9tu/suds-jurko_1ae1d95cd1104cee91119ee45df0c3d1/
    Complete output (1 lines):
    error in suds-jurko setup command: use_2to3 is invalid.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/d0/88/f3bed9b494e0dae26bd55e5f3d527b8244208125024727267e8109956a11/suds-jurko-0.6.zip#sha256=1cb7252cb13018fc32887c3a834ed7c6648a5b5c4c159be5806da2e1785399e8 (from https://pypi.org/simple/suds-jurko/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached suds-jurko-0.6.tar.bz2 (143 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/venv/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-06sba9tu/suds-jurko_5bcb8382fafd4264a54a17e70296b785/setup.py'"'"'; __file__='"'"'/tmp/pip-install-06sba9tu/suds-jurko_5bcb8382fafd4264a54a17e70296b785/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1bibt3g_
         cwd: /tmp/pip-install-06sba9tu/suds-jurko_5bcb8382fafd4264a54a17e70296b785/
    Complete output (1 lines):
    error in suds-jurko setup command: use_2to3 is invalid.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/bd/6f/54fbf0999a606680d27c69b1ad12dfff62768ecb9fe48524cebda6eb4423/suds-jurko-0.6.tar.bz2#sha256=29edb72fd21e3044093d86f33c66cf847c5aaab26d64cb90e69e528ef014e57f (from https://pypi.org/simple/suds-jurko/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached suds-jurko-0.5.zip (220 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/venv/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-06sba9tu/suds-jurko_4d75fecdf45144ca9ccd595284762db0/setup.py'"'"'; __file__='"'"'/tmp/pip-install-06sba9tu/suds-jurko_4d75fecdf45144ca9ccd595284762db0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-lf10vyhk
         cwd: /tmp/pip-install-06sba9tu/suds-jurko_4d75fecdf45144ca9ccd595284762db0/
    Complete output (1 lines):
    error in suds-jurko setup command: use_2to3 is invalid.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/72/22/13c6ff1e731880523ceb7d6137b9450f7cca5b4bee8411017bad23af226c/suds-jurko-0.5.zip#sha256=7ba3267d53b4d5f87a26a4c01efaa01ad85ae620462f0cd72e49d1c340925261 (from https://pypi.org/simple/suds-jurko/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached suds-jurko-0.5.tar.bz2 (122 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/venv/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-06sba9tu/suds-jurko_1bafded84c2948008fcabe9fe2275555/setup.py'"'"'; __file__='"'"'/tmp/pip-install-06sba9tu/suds-jurko_1bafded84c2948008fcabe9fe2275555/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ovxg3qmt
         cwd: /tmp/pip-install-06sba9tu/suds-jurko_1bafded84c2948008fcabe9fe2275555/
    Complete output (1 lines):
    error in suds-jurko setup command: use_2to3 is invalid.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/40/cc/2fad53352898ebfef8b11e4b6b0ef0fac0ee8162c735db28c558d511039c/suds-jurko-0.5.tar.bz2#sha256=3dd119ced5335d71a2844e380e6a509a1f05e6f5bbb5d1f8a2fdf5c74adff8ed (from https://pypi.org/simple/suds-jurko/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement suds-jurko (from versions: 0.4.1.jurko.1, 0.4.1.jurko.2, 0.4.1.jurko.3, 0.4.1.jurko.4, 0.4.1.jurko.5, 0.5, 0.6)
ERROR: No matching distribution found for suds-jurko

**Comment by brenohq** [comment]
Same error here. Any workarround?

**Comment by smallfish01** [comment]
I just using pip3.9 install suds-jurko and it works.

# pip3.9 list
Package    Version
---------- -------
pip        21.2.4
setuptools 57.4.0
suds-jurko 0.6

You may have a try.

Thanks.

**Comment by WhyNotHugo** [comment]
Maybe this is related to https://github.com/pypa/setuptools/issues/2787 ?

**Comment by micah-prime** [comment]
Setuptools>=58 removed support for use_2to3 https://github.com/pypa/setuptools/issues/2086 

Using setuptools<58 is a work around, but not a long term fix.

**Comment by nirhue** [comment]
Hi guys,
any update here? i have tried the above-mentioned workaround for Azure Function App but it didn't work
